# https://docs.codeclimate.com/docs/
# Based on https://gitlab.com/gitlab-org/ci-cd/codequality/-/blob/master/codeclimate_defaults/.codeclimate.yml
---
version: "2"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - go
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true

exclude_patterns:
  - www/3rd
  - "**/*_test.go"
