image: golang:1.14.2-alpine3.11

before_script:
  - apk update
  - apk add gcc libc-dev

test:
  stage: test
  script:
    - go test -coverpkg=gitlab.com/lightmeter/postfix-log-parser,gitlab.com/lightmeter/postfix-log-parser/rawparser -v 2>&1 | go run github.com/jstemmer/go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

cover:
  script:
    - go test -coverpkg=gitlab.com/lightmeter/postfix-log-parser,gitlab.com/lightmeter/postfix-log-parser/rawparser -coverprofile=coverinfo.txt
    - go tool cover -func=coverinfo.txt
  coverage: /^total:\s+.*\s(\d+\.\d+)%$/
