image: alpine:3.11

test:
  stage: test
  before_script:
    - apk update
    - apk add go git
    - go get -u github.com/jstemmer/go-junit-report
  script:
    - go test -v 2>&1 | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml
