image: alpine:3.11

before_script:
  - apk update
  - apk add go git
  - go get -u github.com/jstemmer/go-junit-report

build:
  script:
    - ./build.sh release -a -ldflags "-linkmode external -extldflags '-static' -s -w"
  artifacts:
    paths:
      - ./lightmeter

test:
  script:
    - go test ./... -v 2>&1 | ~/go/bin/go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml
