image: alpine:3.11

before_script:
  - apk update
  - apk add go git
  - go get -u github.com/jstemmer/go-junit-report

build:
  script:
    - ./build.sh release -a -ldflags "-linkmode external -extldflags '-static' -s -w"
  artifacts:
    paths:
      - ./lightmeter

test:
  script:
    - go test -race gitlab.com/lightmeter/controlcenter/... -v 2>&1 | ~/go/bin/go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

cover:
  script:
    - go test ./... -coverprofile=coverinfo.txt
    - go tool cover -func=coverinfo.txt
  coverage: /^total:\s+.*\s(\d+\.\d+)%$/
