run:
  tests: true
  skip-dirs:
    - examples

linters:
  enable-all: true
  disable:
    - gosec
    - testpackage
    - goerr113
    - godox
    - lll
    - gochecknoglobals
    - funlen
    - wsl
    - stylecheck
    - whitespace
    - godot
    - goimports
    - gochecknoinits
    - golint
